/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.10u-20030811-2013
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON
/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#       endif
#endif
#else
#       define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif



#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);

typedef struct swig_type_info {
  const char             *name;                 
  swig_converter_func     converter;
  const char             *str;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
  void                   *clientdata;	
} swig_type_info;

#ifdef SWIG_NOINCLUDE
SWIGEXPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGEXPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGEXPORT(void *) SWIG_TypeCast(swig_type_info *, void *);
SWIGEXPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGEXPORT(void) SWIG_TypeClientData(swig_type_info *, void *);
#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  while (s) {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Cast a pointer (needed for C++ inheritance */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
	if ((strcmp(tc->name, equiv->name) == 0))
	  SWIG_TypeClientData(tc,clientdata);
	tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}
#endif

#ifdef __cplusplus
}
#endif




/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include <stdlib.h>
#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink();
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGEXPORT(int)               SWIG_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGEXPORT(char *)            SWIG_PackData(char *c, void *, int);
SWIGEXPORT(char *)            SWIG_UnpackData(char *c, void *, int);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, swig_type_info *,int own);
SWIGEXPORT(PyObject *)        SWIG_NewPackedObj(void *, int sz, swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, swig_const_info constants[]);
SWIGEXPORT(PyObject *)        SWIG_MakeShadow(PyObject *robj, swig_type_info *type, int own);
#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  (char *)"swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;
  int    newref = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) Py_DECREF(obj);
      return 0;
    } else {
      if (newref) Py_DECREF(obj);
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) Py_DECREF(obj);
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }
  return 0;

type_error:
  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[512];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (own) {
      PyObject *n = PyInt_FromLong(1);
      PyObject_SetAttrString(inst,(char*)"thisown",n);
      Py_DECREF(n);
    }
    robj = inst;
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_MakeShadow(PyObject *robj, swig_type_info *type, int own) {
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyInstanceObject *inst;
    inst = PyObject_NEW(PyInstanceObject, &PyInstance_Type);
    if (!inst) return robj;
    inst->in_dict = PyDict_New();
    inst->in_class = (PyClassObject *) type->clientdata;
    Py_INCREF(inst->in_class);
    PyObject_SetAttrString((PyObject *)inst,(char*)"this",robj);
    Py_DECREF(robj);
    if (own) {
      PyObject *n = PyInt_FromLong(1);
      PyObject_SetAttrString((PyObject *)inst,(char*)"thisown",n);
      Py_DECREF(n);
    }
    robj = (PyObject *) inst;
    Py_INCREF(robj);
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif








/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_uchar swig_types[0] 
#define  SWIGTYPE_p_PyObject swig_types[1] 
#define  SWIGTYPE_p_short swig_types[2] 
#define  SWIGTYPE_p_int swig_types[3] 
static swig_type_info *swig_types[5];

/* -------- TYPES TABLE (END) -------- */

#define SWIG_init    init_onewire

#define SWIG_name    "_onewire"

  typedef unsigned char  uchar;



typedef struct
{
   uchar NumEntries;      // number of entries in path 0-10 
   char  Ref;             // reference character '\' or '.' 
   char  Entries[10][4];  // sub-directory entry names
} DirectoryPath;

typedef struct 
{
   uchar Name[4];          // 4
   uchar Ext;              // 1
   uchar Spage;            // 1
   uchar NumPgs;           // 1
   uchar Attrib;           // 1
   uchar BM[32];           // 32
} FileEntry;



 PyObject *owMyReadFile(int portnum, uchar *INSNum, short hnd, uchar *buf, int maxlen, int *OUTfl_len) {
   if(owReadFile(portnum, INSNum, hnd, buf, maxlen, OUTfl_len))
     return Py_BuildValue("s#",buf,*OUTfl_len);
   else
     return Py_BuildValue("");
 }

extern int owAcquire(int ,char *);
extern void owRelease(int );
extern int owSpeed(int ,int );
extern int owFirst(int ,int ,int );
extern int owNext(int ,int ,int );
extern void owSerialNum(int ,uchar *,int );
extern void PrintSerialNum(uchar *);
extern int owAccess(int );
extern int owOverdriveAccess(int );
extern int owVerify(int ,int );
extern DirectoryPath owGetCurrentDir(int ,uchar *);
extern int owChangeDirectory(int ,uchar *,DirectoryPath *);
extern int owFirstFile(int ,uchar *,FileEntry *);
extern int owNextFile(int ,uchar *,FileEntry *);
extern int owOpenFile(int ,uchar *,FileEntry *,short *);
extern int ReadTemperature(int ,uchar *,float *);
extern int owGetErrorNum(void );
extern void owClearError(void );
extern int owHasErrors(void );
extern void owRaiseError(int );
extern void owPrintErrorMsgStd();
extern uchar *owGetErrorMsg(int );
#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_owAcquire(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    char *arg2 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"is:owAcquire",&arg1,&arg2)) return NULL;
    result = (int )owAcquire(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_owRelease(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    
    if(!PyArg_ParseTuple(args,(char *)"i:owRelease",&arg1)) return NULL;
    owRelease(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_owSpeed(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int arg2 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"ii:owSpeed",&arg1,&arg2)) return NULL;
    result = (int )owSpeed(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_owFirst(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int arg2 ;
    int arg3 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"iii:owFirst",&arg1,&arg2,&arg3)) return NULL;
    result = (int )owFirst(arg1,arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_owNext(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int arg2 ;
    int arg3 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"iii:owNext",&arg1,&arg2,&arg3)) return NULL;
    result = (int )owNext(arg1,arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_owSerialNum(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    uchar *arg2 ;
    int arg3 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"iOi:owSerialNum",&arg1,&obj1,&arg3)) return NULL;
    {
        if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError,"serialnum not a string");
            return NULL;
        }
        arg2 = PyString_AsString(obj1);
    }
    owSerialNum(arg1,arg2,arg3);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        resultobj = Py_BuildValue("s#",arg2, 8);
    }
    return resultobj;
}


static PyObject *_wrap_PrintSerialNum(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    uchar *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:PrintSerialNum",&obj0)) return NULL;
    {
        if (!PyString_Check(obj0)) {
            PyErr_SetString(PyExc_TypeError,"serialnum not a string");
            return NULL;
        }
        arg1 = PyString_AsString(obj0);
    }
    PrintSerialNum(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        resultobj = Py_BuildValue("s#",arg1, 8);
    }
    return resultobj;
}


static PyObject *_wrap_owAccess(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:owAccess",&arg1)) return NULL;
    result = (int )owAccess(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_owOverdriveAccess(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:owOverdriveAccess",&arg1)) return NULL;
    result = (int )owOverdriveAccess(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_owVerify(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    int arg2 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"ii:owVerify",&arg1,&arg2)) return NULL;
    result = (int )owVerify(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_owGetCurrentDir(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    uchar *arg2 ;
    DirectoryPath result;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"iO:owGetCurrentDir",&arg1,&obj1)) return NULL;
    {
        if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError,"insnum not a string");
            return NULL;
        }
        arg2 = PyString_AsString(obj1);
    }
    result = owGetCurrentDir(arg1,arg2);
    
    {
        int i, j;
        DirectoryPath *tmp = &result;
        if (tmp) {
            for(i=0;i<tmp->NumEntries;i++)
            {
                for(j=0;j<4;j++)
                printf("%c",tmp->Entries[i][j]);
                printf("/");
            }
            resultobj = Py_BuildValue("{siss#s{}}",
            "NumEntries",tmp->NumEntries,
            "Ref",tmp->Entries,1,
            "Entries");
            free(tmp);
        }
    }
    return resultobj;
}


static PyObject *_wrap_owChangeDirectory(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    uchar *arg2 ;
    DirectoryPath *arg3 ;
    int result;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"iOO:owChangeDirectory",&arg1,&obj1,&obj2)) return NULL;
    {
        if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError,"insnum not a string");
            return NULL;
        }
        arg2 = PyString_AsString(obj1);
    }
    {
        PyObject *value;
        int i;
        
        arg3 = malloc(sizeof(DirectoryPath));
        
        if(!PyDict_Check(obj2)) {
            PyErr_SetString(PyExc_TypeError,"not a dictionary");
            free(arg3);
            return NULL;
        }
        value = PyDict_GetItem(obj2, Py_BuildValue("s","Ref"));
        if(value)  arg3->Ref = PyString_AsString(value)[0];
        else {
            PyErr_SetString(PyExc_TypeError,"dictionary has missing Ref key");  
            free(arg3);
            return NULL;
        }
        
        value = PyDict_GetItem(obj2, Py_BuildValue("s","Entries"));
        if(value) {
            arg3->NumEntries = PyList_Size(value);
            if ( arg3->NumEntries > 10) {
                PyErr_SetString(PyExc_ValueError,"Too many Entries (max 10)");  
                free(arg3);
                return NULL;
            }else {
                for (i=0; i<arg3->NumEntries; i++) {
                    strncpy(arg3->Entries[i],PyString_AsString(PyList_GetItem(value,i)),4);
                }
            }
        }
        else {
            PyErr_SetString(PyExc_TypeError,"dictionary has missing Entries key");  
            free(arg3);
            return NULL;
        }
    }
    result = (int )owChangeDirectory(arg1,arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_owFirstFile(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    uchar *arg2 ;
    FileEntry *arg3 ;
    int result;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"iOO:owFirstFile",&arg1,&obj1,&obj2)) return NULL;
    {
        if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError,"insnum not a string");
            return NULL;
        }
        arg2 = PyString_AsString(obj1);
    }
    {
        PyObject *value;
        
        arg3 = malloc(sizeof(FileEntry));
        
        if(PyDict_Check(obj2)) {
            value = PyDict_GetItem(obj2, Py_BuildValue("s","Name"));
            if(value) strncpy(arg3->Name,PyString_AsString(value),4);
            else {
                PyErr_SetString(PyExc_TypeError,"dictionary has missing Name key");  
                free(arg3);
                return NULL;
            }
            
            value = PyDict_GetItem(obj2, Py_BuildValue("s","Ext"));
            if(value) arg3->Ext = PyInt_AsLong(value);
            else {
                PyErr_SetString(PyExc_TypeError,"dictionary has missing Name key");  
                free(arg3);
                return NULL;
            }
        }
    }
    result = (int )owFirstFile(arg1,arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    {
        if (arg3) {
            if (arg3->Name[0]) {
                resultobj = Py_BuildValue("{ss#sisisisiss#}",
                "Name",arg3->Name,4,
                "Ext",arg3->Ext,
                "Spage",arg3->Spage,
                "NumPgs",arg3->NumPgs,
                "Attrib",arg3->Attrib,
                "BM",arg3->BM,32);
            }else {
                resultobj =  Py_BuildValue("");
            }
            free(arg3);
        }
    }
    return resultobj;
}


static PyObject *_wrap_owNextFile(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    uchar *arg2 ;
    FileEntry *arg3 ;
    int result;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"iOO:owNextFile",&arg1,&obj1,&obj2)) return NULL;
    {
        if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError,"insnum not a string");
            return NULL;
        }
        arg2 = PyString_AsString(obj1);
    }
    {
        PyObject *value;
        
        arg3 = malloc(sizeof(FileEntry));
        
        if(PyDict_Check(obj2)) {
            value = PyDict_GetItem(obj2, Py_BuildValue("s","Name"));
            if(value) strncpy(arg3->Name,PyString_AsString(value),4);
            else {
                PyErr_SetString(PyExc_TypeError,"dictionary has missing Name key");  
                free(arg3);
                return NULL;
            }
            
            value = PyDict_GetItem(obj2, Py_BuildValue("s","Ext"));
            if(value) arg3->Ext = PyInt_AsLong(value);
            else {
                PyErr_SetString(PyExc_TypeError,"dictionary has missing Name key");  
                free(arg3);
                return NULL;
            }
        }
    }
    result = (int )owNextFile(arg1,arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    {
        if (arg3) {
            if (arg3->Name[0]) {
                resultobj = Py_BuildValue("{ss#sisisisiss#}",
                "Name",arg3->Name,4,
                "Ext",arg3->Ext,
                "Spage",arg3->Spage,
                "NumPgs",arg3->NumPgs,
                "Attrib",arg3->Attrib,
                "BM",arg3->BM,32);
            }else {
                resultobj =  Py_BuildValue("");
            }
            free(arg3);
        }
    }
    return resultobj;
}


static PyObject *_wrap_owOpenFile(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    uchar *arg2 ;
    FileEntry *arg3 ;
    short *arg4 ;
    int result;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    
    {
    }
    if(!PyArg_ParseTuple(args,(char *)"iOO:owOpenFile",&arg1,&obj1,&obj2)) return NULL;
    {
        if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError,"insnum not a string");
            return NULL;
        }
        arg2 = PyString_AsString(obj1);
    }
    {
        PyObject *value;
        
        arg3 = malloc(sizeof(FileEntry));
        
        if(PyDict_Check(obj2)) {
            value = PyDict_GetItem(obj2, Py_BuildValue("s","Name"));
            if(value) strncpy(arg3->Name,PyString_AsString(value),4);
            else {
                PyErr_SetString(PyExc_TypeError,"dictionary has missing Name key");  
                free(arg3);
                return NULL;
            }
            
            value = PyDict_GetItem(obj2, Py_BuildValue("s","Ext"));
            if(value) arg3->Ext = PyInt_AsLong(value);
            else {
                PyErr_SetString(PyExc_TypeError,"dictionary has missing Name key");  
                free(arg3);
                return NULL;
            }
        }
    }
    result = (int )owOpenFile(arg1,arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    {
        if (arg3) {
            if (arg3->Name[0]) {
                resultobj = Py_BuildValue("{ss#sisisisiss#}",
                "Name",arg3->Name,4,
                "Ext",arg3->Ext,
                "Spage",arg3->Spage,
                "NumPgs",arg3->NumPgs,
                "Attrib",arg3->Attrib,
                "BM",arg3->BM,32);
            }else {
                resultobj =  Py_BuildValue("");
            }
            free(arg3);
        }
    }
    {
        resultobj = Py_BuildValue("i",arg4); 
    }
    return resultobj;
}


static PyObject *_wrap_owMyReadFile(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    uchar *arg2 ;
    short arg3 ;
    uchar *arg4 ;
    int arg5 ;
    int *arg6 ;
    PyObject *result;
    PyObject * obj1  = 0 ;
    PyObject * obj3  = 0 ;
    
    {
        arg4 = malloc(65536);
    }
    if(!PyArg_ParseTuple(args,(char *)"iOhO:owMyReadFile",&arg1,&obj1,&arg3,&obj3)) return NULL;
    {
        if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError,"insnum not a string");
            return NULL;
        }
        arg2 = PyString_AsString(obj1);
    }
    if ((SWIG_ConvertPtr(obj3,(void **) &arg6, SWIGTYPE_p_int,1)) == -1) return NULL;
    result = (PyObject *)owMyReadFile(arg1,arg2,arg3,arg4,arg5,arg6);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_PyObject, 0);
    {
    }
    return resultobj;
}


static PyObject *_wrap_owCloseFile(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    uchar *arg2 ;
    short arg3 ;
    int result;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"iOh:owCloseFile",&arg1,&obj1,&arg3)) return NULL;
    {
        if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError,"insnum not a string");
            return NULL;
        }
        arg2 = PyString_AsString(obj1);
    }
    result = (int )owCloseFile(arg1,arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_owCreateFile(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    uchar *arg2 ;
    int *arg3 ;
    short *arg4 ;
    FileEntry *arg5 ;
    int result;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    
    {
    }
    if(!PyArg_ParseTuple(args,(char *)"iOO:owCreateFile",&arg1,&obj1,&obj2)) return NULL;
    {
        if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError,"insnum not a string");
            return NULL;
        }
        arg2 = PyString_AsString(obj1);
    }
    {
        PyObject *value;
        
        arg5 = malloc(sizeof(FileEntry));
        
        if(PyDict_Check(obj2)) {
            value = PyDict_GetItem(obj2, Py_BuildValue("s","Name"));
            if(value) strncpy(arg5->Name,PyString_AsString(value),4);
            else {
                PyErr_SetString(PyExc_TypeError,"dictionary has missing Name key");  
                free(arg5);
                return NULL;
            }
            
            value = PyDict_GetItem(obj2, Py_BuildValue("s","Ext"));
            if(value) arg5->Ext = PyInt_AsLong(value);
            else {
                PyErr_SetString(PyExc_TypeError,"dictionary has missing Name key");  
                free(arg5);
                return NULL;
            }
        }
    }
    result = (int )owCreateFile(arg1,arg2,arg3,arg4,arg5);
    
    resultobj = PyInt_FromLong((long)result);
    {
        resultobj = Py_BuildValue("i",arg4); 
    }
    return resultobj;
}


static PyObject *_wrap_owDeleteFile(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    uchar *arg2 ;
    FileEntry *arg3 ;
    int result;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"iOO:owDeleteFile",&arg1,&obj1,&obj2)) return NULL;
    {
        if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError,"insnum not a string");
            return NULL;
        }
        arg2 = PyString_AsString(obj1);
    }
    {
        PyObject *value;
        
        arg3 = malloc(sizeof(FileEntry));
        
        if(PyDict_Check(obj2)) {
            value = PyDict_GetItem(obj2, Py_BuildValue("s","Name"));
            if(value) strncpy(arg3->Name,PyString_AsString(value),4);
            else {
                PyErr_SetString(PyExc_TypeError,"dictionary has missing Name key");  
                free(arg3);
                return NULL;
            }
            
            value = PyDict_GetItem(obj2, Py_BuildValue("s","Ext"));
            if(value) arg3->Ext = PyInt_AsLong(value);
            else {
                PyErr_SetString(PyExc_TypeError,"dictionary has missing Name key");  
                free(arg3);
                return NULL;
            }
        }
    }
    result = (int )owDeleteFile(arg1,arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    {
        if (arg3) {
            if (arg3->Name[0]) {
                resultobj = Py_BuildValue("{ss#sisisisiss#}",
                "Name",arg3->Name,4,
                "Ext",arg3->Ext,
                "Spage",arg3->Spage,
                "NumPgs",arg3->NumPgs,
                "Attrib",arg3->Attrib,
                "BM",arg3->BM,32);
            }else {
                resultobj =  Py_BuildValue("");
            }
            free(arg3);
        }
    }
    return resultobj;
}


static PyObject *_wrap_owWriteFile(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    uchar *arg2 ;
    short arg3 ;
    uchar *arg4 ;
    int arg5 ;
    int result;
    PyObject * obj1  = 0 ;
    PyObject * obj3  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"iOhOi:owWriteFile",&arg1,&obj1,&arg3,&obj3,&arg5)) return NULL;
    {
        if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError,"insnum not a string");
            return NULL;
        }
        arg2 = PyString_AsString(obj1);
    }
    {
        if (!PyString_Check(obj3)) {
            PyErr_SetString(PyExc_TypeError,"not a string");
            return NULL;
        }
        arg4 = PyString_AsString(obj3);
    }
    result = (int )owWriteFile(arg1,arg2,arg3,arg4,arg5);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_ReadTemperature(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    uchar *arg2 ;
    float *arg3 ;
    int result;
    float temp3 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"iOO:ReadTemperature",&arg1,&obj1,&obj2)) return NULL;
    {
        if (!PyString_Check(obj1)) {
            PyErr_SetString(PyExc_TypeError,"serialnum not a string");
            return NULL;
        }
        arg2 = PyString_AsString(obj1);
    }
    {
        arg3 = &temp3;
    }
    result = (int )ReadTemperature(arg1,arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    {
        resultobj = PyFloat_FromDouble(*arg3);
    }
    return resultobj;
}


static PyObject *_wrap_owGetErrorNum(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)":owGetErrorNum")) return NULL;
    result = (int )owGetErrorNum();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_owClearError(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    
    if(!PyArg_ParseTuple(args,(char *)":owClearError")) return NULL;
    owClearError();
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_owHasErrors(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)":owHasErrors")) return NULL;
    result = (int )owHasErrors();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_owRaiseError(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    
    if(!PyArg_ParseTuple(args,(char *)"i:owRaiseError",&arg1)) return NULL;
    owRaiseError(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_owPrintErrorMsgStd(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    
    if(!PyArg_ParseTuple(args,(char *)":owPrintErrorMsgStd")) return NULL;
    owPrintErrorMsgStd();
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_owGetErrorMsg(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    uchar *result;
    
    if(!PyArg_ParseTuple(args,(char *)"i:owGetErrorMsg",&arg1)) return NULL;
    result = (uchar *)owGetErrorMsg(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_uchar, 0);
    return resultobj;
}


static PyMethodDef SwigMethods[] = {
	 { (char *)"owAcquire", _wrap_owAcquire, METH_VARARGS },
	 { (char *)"owRelease", _wrap_owRelease, METH_VARARGS },
	 { (char *)"owSpeed", _wrap_owSpeed, METH_VARARGS },
	 { (char *)"owFirst", _wrap_owFirst, METH_VARARGS },
	 { (char *)"owNext", _wrap_owNext, METH_VARARGS },
	 { (char *)"owSerialNum", _wrap_owSerialNum, METH_VARARGS },
	 { (char *)"PrintSerialNum", _wrap_PrintSerialNum, METH_VARARGS },
	 { (char *)"owAccess", _wrap_owAccess, METH_VARARGS },
	 { (char *)"owOverdriveAccess", _wrap_owOverdriveAccess, METH_VARARGS },
	 { (char *)"owVerify", _wrap_owVerify, METH_VARARGS },
	 { (char *)"owGetCurrentDir", _wrap_owGetCurrentDir, METH_VARARGS },
	 { (char *)"owChangeDirectory", _wrap_owChangeDirectory, METH_VARARGS },
	 { (char *)"owFirstFile", _wrap_owFirstFile, METH_VARARGS },
	 { (char *)"owNextFile", _wrap_owNextFile, METH_VARARGS },
	 { (char *)"owOpenFile", _wrap_owOpenFile, METH_VARARGS },
	 { (char *)"owMyReadFile", _wrap_owMyReadFile, METH_VARARGS },
	 { (char *)"owCloseFile", _wrap_owCloseFile, METH_VARARGS },
	 { (char *)"owCreateFile", _wrap_owCreateFile, METH_VARARGS },
	 { (char *)"owDeleteFile", _wrap_owDeleteFile, METH_VARARGS },
	 { (char *)"owWriteFile", _wrap_owWriteFile, METH_VARARGS },
	 { (char *)"ReadTemperature", _wrap_ReadTemperature, METH_VARARGS },
	 { (char *)"owGetErrorNum", _wrap_owGetErrorNum, METH_VARARGS },
	 { (char *)"owClearError", _wrap_owClearError, METH_VARARGS },
	 { (char *)"owHasErrors", _wrap_owHasErrors, METH_VARARGS },
	 { (char *)"owRaiseError", _wrap_owRaiseError, METH_VARARGS },
	 { (char *)"owPrintErrorMsgStd", _wrap_owPrintErrorMsgStd, METH_VARARGS },
	 { (char *)"owGetErrorMsg", _wrap_owGetErrorMsg, METH_VARARGS },
	 { NULL, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_uchar[] = {{"_p_uchar", 0, "uchar *"},{"_p_uchar"},{0}};
static swig_type_info _swigt__p_PyObject[] = {{"_p_PyObject", 0, "PyObject *"},{"_p_PyObject"},{0}};
static swig_type_info _swigt__p_short[] = {{"_p_short", 0, "short *"},{"_p_short"},{0}};
static swig_type_info _swigt__p_int[] = {{"_p_int", 0, "int *"},{"_p_int"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_uchar, 
_swigt__p_PyObject, 
_swigt__p_short, 
_swigt__p_int, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0;
    PyObject *m, *d;
    int       i;
    SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    for (i = 0; swig_types_initial[i]; i++) {
        swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
    }
    SWIG_InstallConstants(d,swig_const_table);
    
}

